### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
You did it the better way around, using JS.

I wasnt sure how that worked, even though I saw that code on Greeper

**Comment by TechStudent10** [comment]
@KendallDoesCoding yeah, I learned this technique some time ago. It's cleaner than whatever you just did.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding yeah, I learned this technique some time ago. It's cleaner than whatever you just did.

Yeah, Ik that!

**Comment by TechStudent10** [comment]
haha

**Pull request closed without merging**
