### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Review by TechStudent10 — CHANGES_REQUESTED** [review]
Hmmm, maybe something like "A website for me!" or "My personal portfolio".

**Review by TechStudent10 — CHANGES_REQUESTED** [review]
Maybe remove that note and we will be good to go. Remember, this is a subdomain, however it's also a GitHub site. So there is no need to note that this is a subdomain of github.io.

**Comment by KendallDoesCoding** [comment]
> Maybe remove that note and we will be good to go. Remember, this is a subdomain, however it's also a GitHub site. So there is no need to note that this is a subdomain of github.io.

True

**Comment by TechStudent10** [comment]
Alright all good!

**Comment by KendallDoesCoding** [comment]
Thanks

**Pull request merged**
